[GLOBAL]
print_stacktrace = false

pants_version = "2.6.0rc1"
backend_packages = [
  "pants.backend.python", 
  "pants.backend.python.lint.black", 
  "pants.backend.python.lint.flake8"
]

[source]
root_patterns = [
  "/project-app",
  "/project-models",
]

[python-setup]
interpreter_constraints = ["==3.9.*"]
